import React, { useEffect, useMemo, useState } from "react";
import { api } from "../api";
import { Badge, Button, ConfirmDialog, Input, Modal, ProgressBar, Toast } from "../components/ui";
import { dateRu, today } from "../format";

interface Props { onSyncStateChange: () => void; }
const secretPlaceholder = "Значение сохранено. Оставьте пустым, чтобы не менять";

export default function SettingsScreen({ onSyncStateChange }: Props) {
  const [settings, setSettings] = useState<any>({});
  const [vehicles, setVehicles] = useState<any[]>([]);
  const [sync, setSync] = useState<any>({});
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const load = async () => { const [s,v,p] = await Promise.all([api<any>("settings"),api<any>("vehicles"),api<any>("sync/progress")]); setSettings(s); setVehicles(v.vehicles); setSync(p); };
  useEffect(() => { load().catch(e => setToast({message:e.message,type:"error"})); }, []);
  useEffect(() => { if (!sync.running) return; const timer = setTimeout(() => api<any>("sync/progress").then(setSync), 2500); return () => clearTimeout(timer); }, [sync]);
  const save = async (partial: any, message: string) => { await api("settings", { method:"PUT", body:JSON.stringify(partial) }); setSettings((s:any)=>({...s,...partial})); setToast({message,type:"success"}); };
  return <div className="flex-1 overflow-auto scrollable p-6 flex flex-col gap-5">
    <GlonassSection settings={settings} onSave={save} onToast={setToast} />
    <SheetsSection settings={settings} onSave={save} onToast={setToast} onSynced={load} />
    <VehiclesSection vehicles={vehicles} reload={load} onToast={setToast} />
    <SyncSection sync={sync} setSync={setSync} onSyncStateChange={onSyncStateChange} onToast={setToast} />
    {toast && <Toast message={toast.message} type={toast.type} onClose={()=>setToast(null)} />}
  </div>;
}

function GlonassSection({settings,onSave,onToast}:{settings:any;onSave:(p:any,m:string)=>Promise<void>;onToast:any}) {
  const [form,setForm]=useState<any>({}); const [testing,setTesting]=useState(false); const [status,setStatus]=useState("");
  useEffect(()=>setForm({glonass_login_url:settings.glonass_login_url||"",timezone:settings.timezone||"Europe/Moscow",glonass_username:"",glonass_password:"",glonass_api_key:""}),[settings]);
  const field=(key:string)=>(e:React.ChangeEvent<HTMLInputElement>)=>setForm((f:any)=>({...f,[key]:e.target.value}));
  const test=async()=>{setTesting(true);setStatus("");try{await api("settings/test-glonass",{method:"POST",body:JSON.stringify(form)});setStatus("ok");}catch(e){setStatus(e instanceof Error?e.message:"Ошибка подключения");}finally{setTesting(false);}};
  return <section className="bg-white rounded-lg border border-[#E5E7EB] p-6"><h2 className="text-base font-semibold text-[#243746] mb-4">Подключение к ГЛОНАСС</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
    <Input label="Адрес API" value={form.glonass_login_url||""} onChange={field("glonass_login_url")} /><Input label="Часовой пояс" value={form.timezone||""} onChange={field("timezone")} />
    <Input label="Логин" value={form.glonass_username||""} onChange={field("glonass_username")} placeholder={settings.glonass_username_configured?secretPlaceholder:"Введите логин"} />
    <Input label="Пароль" type="password" value={form.glonass_password||""} onChange={field("glonass_password")} placeholder={settings.glonass_password_configured?secretPlaceholder:"Введите пароль"} />
    <Input label="API-ключ" type="password" value={form.glonass_api_key||""} onChange={field("glonass_api_key")} placeholder={settings.glonass_api_key_configured?secretPlaceholder:"Введите API-ключ"} />
  </div>{status&&<div className={`text-sm mb-3 ${status==="ok"?"text-[#2E7D32]":"text-[#C43D32]"}`}>{status==="ok"?"✓ Подключение установлено":`✗ ${status}`}</div>}<div className="flex gap-3"><Button variant="secondary" loading={testing} onClick={test}>Проверить подключение</Button><Button onClick={()=>onSave(form,"Настройки ГЛОНАСС сохранены").catch((e:any)=>onToast({message:e.message,type:"error"}))}>Сохранить</Button></div></section>;
}

function SheetsSection({settings,onSave,onToast,onSynced}:{settings:any;onSave:any;onToast:any;onSynced:()=>Promise<void>}) {
  const [form,setForm]=useState<any>({});const [testing,setTesting]=useState(false);const [result,setResult]=useState<any>(null);
  useEffect(()=>setForm({google_sheet_urls:(settings.google_sheet_urls?.length?settings.google_sheet_urls:[settings.google_sheet_url].filter(Boolean)).join("\n"),assignments_sheet_name:settings.assignments_sheet_name||"Ввод",vehicle_sheet_name:settings.vehicle_sheet_name||"Справочник",vehicle_model_column:settings.vehicle_model_column||"J",vehicle_plate_column:settings.vehicle_plate_column||"K"}),[settings]);
  const field=(key:string)=>(e:React.ChangeEvent<HTMLInputElement>)=>setForm((f:any)=>({...f,[key]:e.target.value}));
  const payload=()=>({...form,google_sheet_urls:String(form.google_sheet_urls||"").split(/\r?\n/).map(value=>value.trim()).filter(Boolean)});
  const test=async()=>{setTesting(true);try{await onSave(payload(),"Настройки таблиц сохранены");const data=await api<any>("sync/google",{method:"POST",body:"{}"});setResult(data);await onSynced();}catch(e){onToast({message:e instanceof Error?e.message:"Ошибка таблицы",type:"error"});}finally{setTesting(false);}};
  return <section className="bg-white rounded-lg border border-[#E5E7EB] p-6"><h2 className="text-base font-semibold text-[#243746] mb-1">Google Sheets</h2><p className="text-xs text-[#6B7280] mb-4">Можно подключить несколько таблиц. Укажите каждую ссылку с новой строки — разнарядки будут объединены.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><div className="md:col-span-2 flex flex-col gap-1"><label className="text-xs font-medium text-[#374151]">Ссылки на Google-таблицы</label><textarea className="min-h-24 rounded-md border border-[#D1D5DB] bg-white px-3 py-2 text-sm text-[#1F2937] focus:outline-none focus:ring-2 focus:ring-[#2563A6]" value={form.google_sheet_urls||""} onChange={e=>setForm((current:any)=>({...current,google_sheet_urls:e.target.value}))} placeholder="Одна ссылка на строку"/></div><Input label="Вкладка разнарядки" value={form.assignments_sheet_name||""} onChange={field("assignments_sheet_name")}/><Input label="Вкладка справочника" value={form.vehicle_sheet_name||""} onChange={field("vehicle_sheet_name")}/><Input label="Колонка модели автомобиля" value={form.vehicle_model_column||""} onChange={field("vehicle_model_column")}/><Input label="Колонка госномера" value={form.vehicle_plate_column||""} onChange={field("vehicle_plate_column")}/></div>{result&&<div className="text-sm text-[#2E7D32] mb-3">✓ Источников: {result.sources}. Автомобилей: {result.vehicles}. Сотрудников: {result.employees}. Строк разнарядки: {result.assignments}.</div>}<div className="flex gap-3"><Button variant="secondary" loading={testing} onClick={test}>Проверить и обновить</Button><Button onClick={()=>onSave(payload(),"Настройки Google Sheets сохранены").catch((e:any)=>onToast({message:e.message,type:"error"}))}>Сохранить</Button></div></section>;
}

function VehiclesSection({vehicles,reload,onToast}:{vehicles:any[];reload:()=>Promise<void>;onToast:any}) {
  const [search,setSearch]=useState("");const [editing,setEditing]=useState<any>(null);const [deleting,setDeleting]=useState<any>(null);const [adding,setAdding]=useState(false);const [form,setForm]=useState({name:"",plate:""});
  const rows=useMemo(()=>vehicles.filter(v=>v.active&&`${v.name} ${v.plate}`.toLowerCase().includes(search.toLowerCase())),[vehicles,search]);
  const save=async()=>{try{const id=editing?.id;await api(id?`vehicles/${id}`:"vehicles",{method:id?"PUT":"POST",body:JSON.stringify(form)});setEditing(null);setAdding(false);setForm({name:"",plate:""});await reload();onToast({message:id?"Автомобиль обновлён":"Автомобиль добавлен и проверен",type:"success"});}catch(e){onToast({message:e instanceof Error?e.message:"Ошибка",type:"error"});}};
  const remove=async()=>{try{await api(`vehicles/${deleting.id}`,{method:"DELETE"});setDeleting(null);await reload();onToast({message:"Автомобиль удалён из списков и отчётов",type:"success"});}catch(e){onToast({message:e instanceof Error?e.message:"Ошибка",type:"error"});}};
  const check=async(v:any)=>{try{await api(`vehicles/${v.id}/check`,{method:"POST",body:"{}"});await reload();onToast({message:"Совпадение в ГЛОНАСС обновлено",type:"success"});}catch(e){onToast({message:e instanceof Error?e.message:"Ошибка",type:"error"});}};
  const status:any={matched:["success","Найден в ГЛОНАСС"],not_found:["error","Не найден"],ambiguous:["warning","Несколько совпадений"],not_checked:["neutral","Не проверен"]};
  return <section className="bg-white rounded-lg border border-[#E5E7EB] p-6"><h2 className="text-base font-semibold text-[#243746] mb-4">Автомобили</h2><div className="flex gap-3 mb-4"><Button onClick={()=>{setAdding(true);setForm({name:"",plate:""});}}>Добавить автомобиль</Button><input className="h-10 flex-1 max-w-xs rounded-md border border-[#D1D5DB] px-3 text-sm" placeholder="Поиск по названию или номеру" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-x-auto rounded-lg border"><table className="w-full"><thead><tr>{["Название","Госномер","Источник","Название в ГЛОНАСС","Статус","Действия"].map(x=><th key={x} className="text-left text-xs text-[#6B7280] bg-[#F9FAFB] px-3 py-2.5 border-b">{x}</th>)}</tr></thead><tbody>{rows.map(v=>{const [variant,label]=status[v.match_status]||status.not_checked;return <tr key={v.id} className={!v.active?"opacity-50":"hover:bg-[#F9FAFB]"}><td className="px-3 py-3 border-b text-sm">{v.name}</td><td className="px-3 py-3 border-b text-sm font-mono">{v.plate}</td><td className="px-3 py-3 border-b text-sm">{v.manual_override?"Вручную":"Google Sheets"}</td><td className="px-3 py-3 border-b text-sm">{v.glonass_name||"—"}</td><td className="px-3 py-3 border-b"><Badge variant={variant}>{label}</Badge></td><td className="px-3 py-3 border-b text-xs"><button className="text-[#2563A6]" onClick={()=>{setEditing(v);setForm({name:v.name,plate:v.plate});}}>Редактировать</button> · <button className="text-[#6B7280]" onClick={()=>check(v)}>Проверить</button> · <button className="text-[#C43D32]" onClick={()=>setDeleting(v)}>Удалить</button></td></tr>})}</tbody></table></div>
  {(adding||editing)&&<Modal title={editing?"Редактировать автомобиль":"Добавить автомобиль"} onClose={()=>{setAdding(false);setEditing(null)}} footer={<><Button variant="secondary" onClick={()=>{setAdding(false);setEditing(null)}}>Отмена</Button><Button onClick={save}>{editing?"Сохранить и проверить":"Добавить и проверить"}</Button></>}><p className="text-xs text-[#6B7280]">Основное поле для поиска в ГЛОНАСС — государственный номер.</p><Input label="Название или модель" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><Input label="Государственный номер" value={form.plate} onChange={e=>setForm(f=>({...f,plate:e.target.value}))}/></Modal>}
  {deleting&&<ConfirmDialog title="Удалить автомобиль?" message="Автомобиль исчезнет из всех списков и отчётов. Накопленная история останется сохранена в базе." onConfirm={remove} onCancel={()=>setDeleting(null)} confirmLabel="Удалить"/>}</section>;
}

function SyncSection({sync,setSync,onSyncStateChange,onToast}:{sync:any;setSync:any;onSyncStateChange:()=>void;onToast:any}) {
  const [from,setFrom]=useState("2026-07-01"),[to,setTo]=useState(today());
  const start=async()=>{try{const data=await api<any>("sync/all",{method:"POST",body:JSON.stringify({date_from:from,date_to:to})});setSync(data.state);onSyncStateChange();}catch(e){onToast({message:e instanceof Error?e.message:"Ошибка",type:"error"});}};
  const percent=sync.running&&sync.vehicle_total?Math.round((((sync.chunk||1)-1)+sync.vehicle_index/sync.vehicle_total)/Math.max(1,sync.chunks||1)*100):sync.phase==="done"?100:0;const last=sync.last||{};let details:any={};try{details=JSON.parse(last.details||"{}")}catch{}
  return <section className="bg-white rounded-lg border border-[#E5E7EB] p-6"><h2 className="text-base font-semibold text-[#243746] mb-4">Синхронизация</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 text-sm mb-6"><Info label="Последняя синхронизация" value={last.finished_at?new Date(last.finished_at).toLocaleString("ru-RU"):"—"}/><Info label="Статус" value={last.status==="ok"?"Успешно":last.status==="partial"?"Частично (проверьте источник данных)":last.status||"—"}/><Info label="Сохранено дней" value={details.days_saved??"—"}/><Info label="Сохранено событий" value={details.segments_saved??"—"}/></div><div className="border rounded-lg p-4"><h3 className="text-sm font-medium mb-3">Ручная синхронизация</h3><div className="flex flex-wrap items-end gap-3 mb-4"><Input label="С" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input label="По" type="date" value={to} onChange={e=>setTo(e.target.value)}/><Button onClick={start} disabled={sync.running}>{sync.running?"Синхронизация…":"Синхронизировать данные"}</Button></div>{(sync.running||sync.phase==="done")&&<div className="space-y-2"><ProgressBar value={percent} label={`Синхронизация: ${percent}%`}/><div className="text-xs text-[#6B7280]">Период: {dateRu(sync.date_from)}–{dateRu(sync.date_to)} · {sync.vehicle||"обработка завершена"}</div></div>}</div><p className="text-xs text-[#9CA3AF] mt-4">Ежедневно в 02:00 по Москве система перечитывает Google-таблицу и обновляет телеметрию ГЛОНАСС за последние 7 дней.</p></section>;
}
function Info({label,value}:{label:string;value:any}){return <div className="flex justify-between border-b border-[#F3F4F6] py-2"><span className="text-[#6B7280]">{label}</span><b>{String(value)}</b></div>}
